<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Voidwell.Common.Logging</PackageId>
    <Description>Serilog-based logging setup for host applications.</Description>
    <PackageTags>voidwell;logging</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Configuration\src\Voidwell.Common.Configuration\Voidwell.Common.Configuration.csproj" />
  </ItemGroup>

</Project>
